server:
  port: 2026

spring:
  application:
    name: ecommerce-auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

application:
  security:
    jwt:
      secrete-key: abcdefghijklmnopqrstuvwxyz1234567890
      expiration: 987654321
      refresh-token:
        expiration: 897654321

